#H2 settings
spring:
  profiles:
    active: @activatedProperties@
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  servlet:
    context-path: /api
  port: 8090

#axon:
#  axonserver:
#    servers: localhost:8024