spring:
  profiles:
    active: @activatedProperties@
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
server:
  servlet:
    context-path: /api
  port: 8090
