#H2 settings
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  datasource:
    initialization-mode: EMBEDDED
    url: jdbc:h2:file:~/bank_es_cqrs_db
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false